"""User-facing command help text."""


def format_help_text() -> str:
    """Return the /novabot help text."""
    return (
        "🤖 NovaBot - NOVA 社团智能助手\n"
        "━━━━━━━━━━━━━━━━━━━━\n"
        "💬 自然语言交互\n"
        "  直接说话即可，例如：\n"
        "  \"帮我找爬虫教程\"\n"
        "  \"我想学 Python\"\n"
        "  \"社团有哪些作者\"\n"
        "\n"
        "📖 知识库\n"
        "  /kb - 列出知识库\n"
        "  /kb <知识库> - 查看概览\n"
        "  /kb <知识库> <问题> - 范围检索\n"
        "  /kb guide <知识库> - 新人导航\n"
        "  /kb updates <知识库> [天数] - 更新感知\n"
        "\n"
        "📖 同步（管理员）\n"
        "  /sync - 同步全部已启用团队知识库\n"
        "  /sync <team_id> - 只同步指定团队\n"
        "  /sync team <team_id> - 只同步指定团队\n"
        "  /sync members - 同步全部已启用团队成员\n"
        "  /sync members <team_id> - 同步指定团队成员\n"
        "  /sync status - 同步状态\n"
        "  /sync collab - 更新协作网络\n"
        "  /rag search <关键词> - 语义搜索\n"
        "  /webhook - Webhook 服务状态\n"
        "\n"
        "👤 账号\n"
        "  /bind <用户名> - 绑定账号\n"
        "  /unbind - 解除绑定\n"
        "  /profile - 查看画像\n"
        "  /profile refresh - 刷新画像\n"
        "  /profile assess <领域> - 领域评估\n"
        "  /persona - 人设偏好设置\n"
        "\n"
        "👥 伙伴与学习\n"
        "  /partner - 学习伙伴推荐\n"
        "  /partner <主题> - 按主题推荐\n"
        "  /path <领域> - 学习路径推荐\n"
        "  /card <主题> - 知识卡片\n"
        "\n"
        "🔔 订阅\n"
        "  /subscribe - 查看订阅\n"
        "  /subscribe repo <知识库> - 订阅知识库\n"
        "  /subscribe author <作者> - 订阅作者\n"
        "  /unsubscribe <ID> - 取消订阅\n"
        "\n"
        "📊 分析\n"
        "  /weekly - 本周知识周报（管理员）\n"
        "  /weekly raw - 导出按周原始统计 CSV（管理员）\n"
        "  /gap - 知识缺口分析\n"
        "  /tokens - Token 消耗统计\n"
        "\n"
        "💬 知识问答\n"
        "  /ask <问题> - 提问（需绑定）\n"
        "  /ask list - 查看问题列表\n"
        "  /ask view <ID> - 查看详情\n"
        "  /ask answer <ID> <回答> - 回答（需绑定）\n"
        "  /ask like <问题ID> <回答ID> - 点赞\n"
        "  /ask mine - 我的问题\n"
        "  /ask delete <ID> - 删除我的问题\n"
        "  /askreset - 重置提问箱（管理员）\n"
        "\n"
        "🧠 记忆\n"
        "  /memory - 查看记忆概览\n"
        "  /memory recent - 最近对话\n"
        "  /memory search <关键词> - 搜索对话\n"
        "  /memory clear - 清除记忆\n"
        "\n"
        "📈 学习进度\n"
        "  /progress - 查看学习进度\n"
        "  /progress <领域> - 查看指定领域\n"
        "  /progress add <领域> <事件> - 添加里程碑\n"
        "\n"
        "❓ 问题档案\n"
        "  /questions - 未解决的问题\n"
        "  /questions all - 所有问题\n"
        "  /questions frequent - 反复出现的问题\n"
        "  /questions resolve <ID> - 标记已解决\n"
        "\n"
        "👣 成员轨迹\n"
        "  /trajectory - 查看自己的活动轨迹\n"
        "  /trajectory <成员名> - 查看指定成员轨迹\n"
        "  /trajectory topic <主题> - 主题相关活动\n"
        "\n"
        "🤝 协作网络\n"
        "  /collab - 查看自己的协作伙伴\n"
        "  /collab <成员名> - 查看指定成员协作伙伴\n"
        "  /collab find <主题> - 寻找协作伙伴\n"
        "\n"
        "  /novabot - 帮助"
    )
